### ISSUE TITLE
未登录模式，如何做权限校验

### ISSUE THREAD

**Issue by walle233** [nasawz/niceup#1]
如题，web端 未登录模式下，直接调用 sdk 操作云数据库，如何做权限校验比较合理。

**Comment by nasawz** [comment]
以下配置是我的方案


         {
              "collectionName": "Notice",
              "aclTag": "CUSTOM",
              "aclRule": {
                "read": true,
                "write": "auth.uid in get(`database.Admin.user`).admin"
              }
            },

开放读取，需要写入时验证当前登录的用户id是否存在Admin表中。

**Comment by walle233** [comment]
不错，谢谢解答
