### ISSUE TITLE
NoSuchKey 

### ISSUE THREAD

**Issue by Z000204** [nasawz/niceup#2]
Code: NoSuchKey
Message: The specified key does not exist.
Key: mini-site/index.html

**Comment by nasawz** [comment]
需要配合腾讯云开发

**Comment by Z000204** [comment]
我把客户端实现了，但是小程序总是说没有index.html

**Comment by nasawz** [comment]
是根目录打开的不 ？

**Comment by nasawz** [comment]
![image](https://user-images.githubusercontent.com/372910/164250353-a2975b5a-2750-4c32-a73d-ff1bdc574126.png)

**Comment by nasawz** [comment]
参考上图
