### ISSUE TITLE
部署不成功

### ISSUE THREAD

**Issue by eminfan** [nasawz/niceup#3]
![image](https://user-images.githubusercontent.com/16729869/191286341-60909a1c-8f9d-4466-9721-634e7fa9dcfb.png)
现在是上海2服务器， 总是找不到
明明有环境， 却说没有

**Comment by nasawz** [comment]
放弃云开发吧   运维成本翻了100倍    官方的bug也不怎么修

溜了 溜了

**Comment by nasawz** [comment]
看好lafjs   以后有机会了迁移过去

**Comment by GiantappMan** [comment]
必须放弃，功能不改，价格涨的飞快
